data_pack:
  load: .
  min_format: [121,0]
  max_format: [121,0]
  pack_format: 121

resource_pack:
  load: .
  min_format: [97,1]
  max_format: [97,1]
  pack_format: 97

pipeline:
  - mecha

"description": [
  {"text":"\u26cf Jake's Build Tools \u26cf", "color":"#04b9ff"},
  {"text":"\n"},
  {"text":"Tools to make building easy","color":"#7e7e7e"}
]